### ISSUE TITLE
Blazor Testing Library Discovery

### ISSUE THREAD

**Issue by claytonleonardcook** [SVSU-Capstone25/PLOT-FE#1]

**Comment by bbpearsall** [comment]
bUnit is a testing library that is designed to handle C#, which is perfect for Blazor development.

**Comment by kai-kaldahl** [comment]
If we're basing testing solely on C# I've seen xUnit (https://xunit.net/) be mentioned for testing, but I think bUnit would be best for our purposes.

**Comment by pmdurfee** [comment]
Something to note, bUnit CANNOT do End to End testing, nor can it test browser specific functionality. Once testing is done, using bUnit, we would have to do other testing via actual browsers to see if any behavior changes. While it shouldn't change, it's still good to check.

**Comment by pratham-patell** [comment]
We should be able to use Selenium for end to end testing. Selenium is well-suited for testing user interactions and browser-specific functionality. 

https://www.selenium.dev/

**Comment by mdloucks** [comment]
It seems like the group is leaning towards bUnit for unit tests. I'm going to make a small bUnit POC to add to our Github pipelines.

**Comment by claytonleonardcook** [comment]
Hey guys, I remember seeing Playwright on some projects I've worked on in the past and I thought it was only for JavaScript but it seems to also have a .NET implementation. Maybe this is something we could use?

https://playwright.dev/dotnet/

It also seems like they have a CLI that we could use with GitHub Actions to run the tests automatically.

https://github.com/microsoft/playwright-github-action

Also, C# has built in unit testing but it's kind of annoying since it has to be another project alongside the other?

https://learn.microsoft.com/en-us/visualstudio/test/walkthrough-creating-and-running-unit-tests-for-managed-code?view=vs-2022

**Comment by claytonleonardcook** [comment]
The bUnit stuff pretty much has the same structure though? Also, I did find a YAML for a GitHub Action that we could use to run the testing. I guess it's just using the .NET CLI.

```yaml
name: Run bUnit Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test --configuration Release --no-restore
```
